name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm install
      
      - name: Debug - Check installations
        run: |
          echo "=== Checking tone installation ==="
          npm list tone
          echo "=== Checking node_modules/tone ==="
          ls -la node_modules/tone/ || echo "tone directory not found"
          echo "=== Checking tone package.json ==="
          cat node_modules/tone/package.json || echo "package.json not found"
          echo "=== Checking if Tone.js files exist ==="
          ls -la node_modules/tone/build/ || echo "build directory not found"
      
      - name: Build
        run: npm run build
        env:
          PUBLIC_URL: /interactive-orchestra
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
